# Naive Bayes

In [1]:
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np
from sklearn.calibration import CalibratedClassifierCV


iris = datasets.load_iris()
feature = iris.data
target = iris.target

C:\Users\Administrator\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


## Training a Classifier the Continuous Features

In [3]:
classifer = GaussianNB()
model=classifer.fit(feature, target)
model.predict([[4,4,4,0.4]])

array([1])

In [4]:
clf = GaussianNB(priors=[0.25,0.25,0.5])
model = clf.fit(feature, target)

naive_bayes model's predict_proba method is not calibred so we cannont believe in it.

## Training a Classifier for Discrete and Count Features

In [7]:
text_data = np.array(['I love Brazil. Brazil!', 'Brazil is best', 'Germany beats both'])
count = CountVectorizer()
bag_of_words = count.fit_transform(text_data)
features = bag_of_words.toarray()
targets = np.array([0,0,1])
classifier = MultinomialNB(class_prior=[0.25, 0.5])
model = classifier.fit(features, targets)

In [8]:
new_observation = [[0,0,0,1,0,1,0]]
model.predict(new_observation)

array([0])

## Training a Classifier for Binary Features

In [9]:
features = np.random.randint(2, size=(100, 3))
targets = np.random.randint(2, size=(100, 1)).ravel()
classifier = BernoulliNB(class_prior=[0.25, 0.5])
model = classifier.fit(features, targets)

In [10]:
model_uniform_prior = BernoulliNB(class_prior=None, fit_prior=True)

## Calibrating Predicted Probabilities

In [12]:
classifier = GaussianNB()
classifier_sigmoid = CalibratedClassifierCV(classifier, cv=2, method='sigmoid')
classifier_sigmoid.fit(feature, target)
new_observation=[[2.6, 2.6, 2.6, 0.4]]
classifier_sigmoid.predict_proba(new_observation)

array([[0.31859969, 0.63663466, 0.04476565]])

In [13]:
classifier.fit(feature, target).predict_proba(new_observation) # which is not calibrated... so we cannot trust it....

array([[2.31548432e-04, 9.99768128e-01, 3.23532277e-07]])