# Matrix,Vectors,Arrays

## 1.1 Creating a Vector

In [1]:
import numpy as np
vector_row = np.array([[1,2,3]])
vector_column = np.array([[1]
                         ,[2]
                         ,[3]])
vector_row, vector_column

(array([[1, 2, 3]]),
 array([[1],
        [2],
        [3]]))

In [2]:
# tips you can transfer a one-dimensional row vector easily to the column vector
vector_rows = np.array([1,2,3])
vector_rows[:,np.newaxis], vector_rows[np.newaxis,:]

(array([[1],
        [2],
        [3]]),
 array([[1, 2, 3]]))

## 1.2 Creating a Matrix

In [3]:
matrix_A = np.array([[2,1],
                     [1,3]])
matrix_A

array([[2, 1],
       [1, 3]])

In [4]:
matrix_B = np.mat([[1,3],
                   [2,5]])
matrix_B
# Not recommended!!!!

matrix([[1, 3],
        [2, 5]])

## 1.3 Creating a Sparse Matrix

In [5]:
from scipy import sparse
matrix_C = np.array([[0,0,0],[0,0,1],[1,2,0]])
matrix_sparse = sparse.csr_matrix(matrix_C)
print(matrix_sparse)

  (1, 2)	1
  (2, 0)	1
  (2, 1)	2


## 1.4 Selecting Elements

In [6]:
arr1 = np.arange(36).reshape(6,6)
arr2 = np.arange(6)
arr1, arr2

(array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]),
 array([0, 1, 2, 3, 4, 5]))

### scalar index

In [7]:
arr2[2], arr1[2,3]  # rows: 3 columns: 4

(2, 15)

### tuple index

In [8]:
arr1[(2,1),(1,3)]

array([13,  9])

### slice index

In [9]:
arr1[1:3,1:4]

array([[ 7,  8,  9],
       [13, 14, 15]])

### boolean index

In [10]:
arr1[arr1>20]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35])

### 1.5 Describing a Matrix

In [12]:
arr3 = np.arange(12).reshape(3,4)
arr3, arr3.shape, arr3.size, arr3.ndim

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 (3, 4),
 12,
 2)

### 1.6 Applying Operation to Elements

In [13]:
add_100 = lambda x: x+100
vectorized_add_100 = np.vectorize(add_100)
vectorized_add_100(arr3)

array([[100, 101, 102, 103],
       [104, 105, 106, 107],
       [108, 109, 110, 111]])

We can also achieve the same goal by using **broadcasting** process. 

In [14]:
arr3 + 100

array([[100, 101, 102, 103],
       [104, 105, 106, 107],
       [108, 109, 110, 111]])

### 1.7 Finding the Maximum and Minimum Values

In [15]:
np.min(arr3), np.max(arr3)

(0, 11)

Using the `axis` parameter we can also apply the operation along a certain axis

In [16]:
np.min(arr3, axis=0), np.min(arr3,axis=1),np.max(arr3,axis=0),np.max(arr3,axis=1)

(array([0, 1, 2, 3]),
 array([0, 4, 8]),
 array([ 8,  9, 10, 11]),
 array([ 3,  7, 11]))

### 1.8 Average,Vairiance,and Standard Deviation

In [17]:
np.mean(arr3),np.var(arr3),np.std(arr3)

(5.5, 11.916666666666666, 3.452052529534663)

Like `min`, `max` operation, `mean`,`var`,`std` also have the `axis` parameter

In [18]:
np.mean(arr3, axis=0)

array([4., 5., 6., 7.])

### 1.9 Reshaping Arrays

In [19]:
arr3.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

also `reshape` method accept negative integer which means "as many as needed"

In [20]:
arr3.reshape(2,-1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

### 1.10 Transposing a Vector or Matrix

In [21]:
arr3.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [22]:
vector_row.T

array([[1],
       [2],
       [3]])

<font color=#FE2D00><b> Warning: apply T to one-dimensional array doesnot have any effect!</b></font>

In [25]:
vector_rows.T

array([1, 2, 3])

### 1.11 Flattening a Matrix

In [26]:
arr3.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
# transfer to two-dimensional matrix
arr3.reshape(1,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

### 1.12 Finding the Rank of a Matrix

In [28]:
np.linalg.matrix_rank(arr3)

2

### 1.13 Calculating the Determinant

In [29]:
arr1, np.linalg.det(arr1)

(array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]),
 0.0)

### 1.14 Getting the diagonal of a matrix

In [30]:
arr1.diagonal()

array([ 0,  7, 14, 21, 28, 35])

Use parameter `offset` to get a diagonal from the main diagonal.

In [31]:
arr1.diagonal(offset=1), arr1.diagonal(offset=-1)

(array([ 1,  8, 15, 22, 29]), array([ 6, 13, 20, 27, 34]))

### 1.15 Calculating the Trace of a Matrix

In [33]:
arr1.trace(), sum(arr1.diagonal())

(105, 105)

### 1.16 Finding Eigenvalues and Eigenvectors

In [34]:
eigenvalues, eigenvectorss = np.linalg.eig(arr1)
eigenvalues, eigenvectorss

(array([ 1.10691494e+02+0.00000000e+00j, -5.69149422e+00+0.00000000e+00j,
        -2.66999242e-15+0.00000000e+00j,  1.81659945e-15+1.08757519e-15j,
         1.81659945e-15-1.08757519e-15j, -3.29703186e-16+0.00000000e+00j]),
 array([[ 0.06671357+0.j        , -0.63270151+0.j        ,
          0.5214368 +0.j        ,  0.14515996-0.07004585j,
          0.14515996+0.07004585j, -0.08976992+0.j        ],
        [ 0.18278485+0.j        , -0.39467352+0.j        ,
         -0.4446138 +0.j        , -0.3150858 +0.20533019j,
         -0.3150858 -0.20533019j, -0.00095334+0.j        ],
        [ 0.29885614+0.j        , -0.15664552+0.j        ,
         -0.03649591+0.j        , -0.01995886-0.10578275j,
         -0.01995886+0.10578275j,  0.65699274+0.j        ],
        [ 0.41492743+0.j        ,  0.08138247+0.j        ,
         -0.57579175+0.j        , -0.08060649-0.07687162j,
         -0.08060649+0.07687162j, -0.65874641+0.j        ],
        [ 0.53099872+0.j        ,  0.31941047+0.j        ,
     

### 1.17 Calculating Dot Products

In [36]:
np.dot(vector_row, vector_column) # not recommended...cos it generates a matrix(1,1)

array([[14]])

In [40]:
np.dot(vector_row[0,:], vector_column[:,0]) # this is dot product

14

In [43]:
arr3, np.dot(vector_row, arr3)

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[32, 38, 44, 50]]))

### 1.18 Adding and Subtracting Matrix

In [46]:
np.add(arr3, arr3),np.subtract(arr3,arr3)

(array([[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22]]),
 array([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]))

### 1.19 Inverting a Matrix

In [47]:
matrix_B = np.array([[1,4],
                    [2,5]])
np.linalg.inv(matrix_B)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

### 1.20 Generating Random Values

#### generating random floats between 0.0 and 1.0

In [48]:
np.random.seed(0)
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

In [50]:
np.random.random(size=(3,3)) # generate a random matrix...

array([[0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492]])

#### generating random integers between a and b

In [51]:
np.random.randint(0, 11, size=(3,3))

array([[8, 1, 5],
       [9, 8, 9],
       [4, 3, 0]])

#### generating normalize elements with fixed mean and variance

In [52]:
np.random.normal(0.0, 1.0, size=(3,4))

array([[ 0.48431215,  0.57914048, -0.18158257,  1.41020463],
       [-0.37447169,  0.27519832, -0.96075461,  0.37692697],
       [ 0.03343893,  0.68056724, -1.56349669, -0.56669762]])

#### generating logistic distribution with mean

In [53]:
np.random.logistic(0, 1, size=(3,3))

array([[ 1.23237331, -0.17585043,  0.27546455],
       [-3.95547251,  0.47952412,  0.45613008],
       [ 0.47655474,  2.82001906,  0.76214981]])

#### generating random floats between a and b

In [54]:
np.random.uniform(1, 2, size=(2,4))

array([[1.3595079 , 1.43703195, 1.6976312 , 1.06022547],
       [1.66676672, 1.67063787, 1.21038256, 1.1289263 ]])